# Generated by Django 4.2.4 on 2024-03-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('national_id', models.IntegerField()),
                ('social_link', models.TextField(null=True)),
                ('agentImage', models.ImageField(upload_to='agentImages/')),
                ('Agent_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('hs_name', models.CharField(default='Master en suite', max_length=200)),
                ('hs_Category', models.CharField(choices=[('houserentals', 'rent-house'), ('housesale', 'sell-house')], max_length=50)),
                ('hs_Location', models.TextField()),
                ('hs_Price', models.IntegerField(default=0, null=True)),
                ('hs_image', models.ImageField(upload_to='properties/house')),
                ('hs_advertising_date', models.DateTimeField(auto_now_add=True)),
                ('hs_last_check', models.DateTimeField(auto_now=True)),
                ('hs_bed_rooms', models.IntegerField()),
                ('hs_others', models.TextField(null=True)),
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HouseOlx.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('la_category', models.CharField(choices=[('landlease', 'rent-land'), ('landsell', 'sell-land')], max_length=40)),
                ('la_Location', models.TextField()),
                ('la_Price', models.IntegerField()),
                ('land_image', models.ImageField(upload_to='properties/land')),
                ('advertising_date', models.DateTimeField(auto_now_add=True)),
                ('la_width', models.IntegerField()),
                ('la_height', models.IntegerField()),
                ('Land_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HouseOlx.agent')),
            ],
        ),
        migrations.CreateModel(
            name='property_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(choices=[('notsatisfactory', '1'), ('almost_there', '2'), ('fair', '3'), ('above_average', 4), ('great', '5')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('hs_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HouseOlx.house')),
                ('la_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HouseOlx.land')),
            ],
        ),
    ]
